### ISSUE TITLE
active option at page level

### ISSUE THREAD

**Issue by tidiview** [bgartenmann/grav-plugin-simple-responsive-tables#1]
First, thank you very much for your work ♪

Correct if wrong, actually, the grav-plugin-simple-responsive-tables is all or nothing: for a table on a page, it has to enable it for entire site.
So here is a suggestion to add a option to enabled at a page level like for the [grav-plugin-shortcode-core](https://github.com/getgrav/grav-plugin-shortcode-core) that you probably already know.

The precise part of code concerned might be [that](https://github.com/getgrav/grav-plugin-shortcode-core/blob/ff79e350733acc0cb0e5a7488fa7eabe82aa3734/shortcode-core.php#L120), but I am not quite sure.

I am not that personnally so skilled that I can code it and make a pull request immediatly, so please forgive me for that; I would like to do such setting also for my own [plugin](https://github.com/tidiview/grav-plugin-markdown-rubytext) in the future too.

Tidiview

**Comment by bgartenmann** [comment]
Hi Tidiview,
thanks for your suggestion. This is definitely something I could improve.
You're right, at the moment it is all or nothing. It is enabled for the entire site and also loads the corresponding css and js files on every page, even if there isn't any table... 
I will try to look into it the next few days.
Beni

**Comment by tidiview** [comment]
Thank you very much for quick answering.
I'll look foward to it, in order to offer the same functionality to [mine](https://github.com/tidiview/grav-plugin-markdown-rubytext).
Tidiview

**Comment by bgartenmann** [comment]
This is now possible with v1.1.0
See commit fe58c29 for the implementation
